version: '3'

services:
  redis:
    image: "redis:alpine"
  web:
    build: ./core
    command: bash -c "python /var/app/manage.py migrate --noinput && python /var/app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./core:/var/app
    ports:
      - 8000:8000
    depends_on:
      - redis
  celery:
    build: ./core
    command: celery -A core worker -l info
    volumes:
      - ./core:/var/app
    depends_on:
      - redis
